### ISSUE TITLE
Implement mechanism to record somatic voltages for all cells in a simulation

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#181]
The purpose of this issue is to replicate the end result of displaying somatic voltages for all cells, as in HNN. Required by https://github.com/jonescompneurolab/hnn/issues/231

Some of the needed functionality to record somatic voltages of cells already exists in
https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/cell.py#L219-L237

However, it is only used for simulating a single cell. HNN needs this done for all cells with a high-level mechanism.
https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/cell.py#L331

Suggest preserving the `save_vsoma` param, which can in turn set up recording for each cell on network creation, similar to below
https://github.com/jonescompneurolab/hnn/blob/master/network.py#L288

Lastly, aggregating all of the voltages for writing was parallelized in HNN. Not sure how long it takes otherwise.
https://github.com/jonescompneurolab/hnn/blob/master/run.py#L100-L114

**Comment by blakecaldwell** [comment]
Related to https://github.com/jonescompneurolab/hnn-core/issues/121. I don't know exactly what the bug is referring to. Seems like a feature enhancement as proposed here?

**Comment by jasmainak** [comment]
I think the bug is that you don't want to have a current input when the cell is connected to other cells in the network?

I think it might be better if the voltages can be added as an attribute of the `Network` object rather than being saved. In an ideal world, it should be part of the cell object which is transparently accessible but we're not there yet, so I can live with an okay solution.
