### ISSUE TITLE
MPIBackend does not allow passing whole objects

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#210]
Currently, the MPIBackend passes the `params` dictionary to the child for running simulations. I think we should allow passing arbitrary Python objects as long as they are picklable. This will make it more similar to the Joblibs backend and also not limit code design. @blakecaldwell do you have an intuition whether this is easy/difficult to implement.

[Discovered this](https://github.com/jonescompneurolab/hnn-core/pull/199#discussion_r528268228) in #199 with @ntolley

**Comment by blakecaldwell** [comment]
Conceptually, I think it's fine to pass an arbitrary Python object rather than a dictionary. Important though that it should be a single object (e.g `SimulationInput`). This could nest other objects inside though. The reason is that there is a "protocol" for sending objects. After sending is complete, the simulation can begin. Having a single object that gets pickled and sent is just a simple protocol. 

Arbitrary combinations are technically possible, but you need to carefully match code between what `MPIBackend` sends and `mpi_child` receives. You would use a signal that tells the child all data has been transferred and a simulation can begin. The signal would be analogous to what is done when a simulation is finished. However, recall the complexity that required.

This would be a good project for someone to pick up to become familiar with the MPI code. I suggest starting simple (a single object) to get comfortable with the code before implementing something more elaborate.

**Comment by jasmainak** [comment]
implemented in #211 :) I guess it should also be straightforward to extend to multiple function arguments by passing a dictionary ...

**Comment by jasmainak** [comment]
Moving to 0.2 ... I'm really under the water with grant writing at the moment

**Comment by jasmainak** [comment]
I think this was addressed by @cjayb in #221
