### ISSUE TITLE
documentation for different versions

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#277]
We should archive the 0.1 and make CircleCI push directly to 0.2.dev0 and there should be a tab in the navbar for this

@sappelhoff can I solicit your help for this? I remember you did this for mne-bids! What do we need to do?

**Comment by sappelhoff** [comment]
I can tell you the individual elements that are needed :-) 


# A circleci deploy job:

https://github.com/mne-tools/mne-bids/blob/a45695ed43394f067a776f0f51441723915bcbf5/.circleci/config.yml#L61-L85

# a sphinx layout extension (assuming you are using the bootstrap theme for hnn-core):

https://github.com/mne-tools/mne-bids/blob/a45695ed43394f067a776f0f51441723915bcbf5/doc/_templates/navbar.html#L1-L22

# a gh-pages branch with a tree looking like this:

https://github.com/mne-tools/mne-bids/tree/gh-pages

most importantly an `index.html` that redirects to a subfolder in tre tree: https://github.com/mne-tools/mne-bids/blob/c758651f6deb40888a4b6651a7062d999673f633/index.html#L1-L14


each of these folders is a version of the docs ... and the most recent *stable* version is duplicated --> once in a folder called `stable`, and once in a folder `vX.X` (replace X.X), so that from any version of the docs you can switch to the current "stable" version

# See the docs

I wrote documentation about this here: https://github.com/mne-tools/mne-bids/wiki/Explanation-of-Documentation-Setup

**Comment by jasmainak** [comment]
amazing, thanks @sappelhoff for the run down! I made the PRs in #278 and #279 . Do you mind taking a look? I am assuming #279 should be merged first?

**Comment by sappelhoff** [comment]
yes, #279 needs to go in first :+1: and then #278 should be good to go
