### ISSUE TITLE
nmda weights for proximal drives

### ISSUE THREAD

**Issue by andererka** [jonescompneurolab/hnn-core#461]
Hi, I tried to add nmda weights for the proximal drives using the jones2009 model. In your examples, you set the nmda weights to None for the proximal drives and I didn't succeed in setting them so far. So, I was wondering, if this is possible for the jones2009 model in general. In your optimization tutorial, you also optimize for it and mention that L5 basket nmda is an important parameter for proximal drive1, so I also wanted to include it in my simulation experiment. 
Should I use a different model then or do you have an idea what the issue could be?

**Comment by rythorpe** [comment]
You should be able to specify the `weights_nmda` argument in the `net.add_evoked_drive()` function. For instance, if you modify the [plot_simulate_evoked.py](https://github.com/jonescompneurolab/hnn-core/blob/c224697c6ff1e16078587053c8bfc5e5e8b97182/examples/workflows/plot_simulate_evoked.py#L75) example such that the NMDA weights of the first proximal drive match those of the AMPA weights of the same drive, (`weights_nmda=weights_ampa=weights_ampa_p2`), you should get something that looks like this (left, original; right, modified):

![image](https://user-images.githubusercontent.com/20212206/152192630-d94d6ee5-b052-4670-a508-79480df0224b.png)

Notice how increasing the NMDA weights pronounces the prominent trough at ~70 ms in the blue trace. This is most likely due to the influence of prolonged NMDA-mediated activation of L5 basket cells in particular.

**Comment by andererka** [comment]
Thanks a lot for the fast response. I did set the nmda weights like you described above in the same way as with the ampa weigths, but I get a key error for 'KeyError: 'L5_pyramidal''. That's why I thought that the model maybe does not allow for setting the nmda weights for proximal drives.

**Comment by andererka** [comment]
So, strangely, the simulation works now and I am not sure what the reason for the issue was. Thanks a lot for your help. 
We can close the issue, I guess

**Comment by rythorpe** [comment]
No worries, glad it's working! I'm guessing you ran into a check we have built into the API that enforces that the cell types specified for AMPA weights must be the same for NMDA weights (i.e., `weights_ampa.keys() == weights_nmda()`), so if you specified an NMDA dict who's keys don't match those of the AMPA dict, it'll throw an error.

**Comment by andererka** [comment]
Yes! Thanks! That was very helpful. This was exactly the reason for the error.
