### ISSUE TITLE
Variation in firing of L2/3 Pyramidal cells between trials

### ISSUE THREAD

**Issue by mkhalil8** [jonescompneurolab/hnn-core#631]
Hi @jasmainak , @ntolley  and everyone,

what explains the big variability in L2/3 pyramidal firing with trials? and why their firing that is usually around 120msecs (supposedly caused by the Distal input) is delayed from the mean of most of the distal input?
I understand that the Vecstim objects connectivity to the different populations of cells is distributed and that the main change in between trials is the seeds (incremented by 1 as I remember) which changes the timing of the spiking input.
These are 25 trials using Kohl's auditory ERP parameters.
 
![Screen Shot 2023-03-31 at 1 13 08 PM](https://user-images.githubusercontent.com/14954705/229186352-f8667b8c-7acc-495f-8139-83769ab2336b.png)

**Comment by rythorpe** [comment]
The variability you're observing is caused by local network interactions. The local network connectivity to and from L2/3 pyramidal cells (specifically the L2/3 basket -> L2/3 pyramidal and L5 pyramidal -> L2/3 pyramidal connections) makes their firing particularly sensitive to small variations in exogenous drive timing. Notice the following sequence of events:

1.  an initial barrage of L2/3 pyramidal spikes (dark green I'm assuming) occurs at ~50 ms robustly across trials
2. L2/3 pyramidal firing is quickly squashed by inhibition from L2/3 basket cell firing (light green I'm assuming)
3. L2/3 basket cells fire a little here and there from 50-100 ms, and are easily excited by exogenous drive + L5 pyramidal spiking that builds over time
4. when the strong distal drive hits, L5 pyramidal spiking increases drastically that then propagates throughout the network
5. L2/3 pyramidal cells are mostly silenced from 50-100 ms, unless they are transiently released from L2/3 basket inhibition or until L5 pyramidal firing reaches a critical mass that overcomes them with local network excitation

Altogether, L2/3 pyramidal spiking rests right near the threshold of local network E/I balance. The tight coupling between L2/3 pyramidal and L2/3 basket cells also allows for pyramidal interneuron gamma (PING) activity to emerge transiently. All that said, I encourage you to play around with the local network connectivity parameters in order to test my assertions above (e.g., try increasing the L5 pyramidal -> L2/3 pyramidal weight to test the hypothesis that the ~120 ms barrage of L2/3 pyramidal spikes shifts left and with greater temporal consistency/precision).

**Comment by rythorpe** [comment]
I'm going to convert this to a discussion, but feel free to open another issue if you end up finding a bug.
