### ISSUE TITLE
[BUG] `plot_dipole` not showing in GUI with `matplotlib>=3.8.0` 

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#694]
Reproduced by creating a new conda environment and doing a fresh `pip install hnn_core[gui]`. Simulation outputs will look like:
![image](https://github.com/jonescompneurolab/hnn-core/assets/55253912/ceb09ef2-2bcf-45fa-82c1-81e352847c7e)

Normal functionality is restored by downgrading matplotlib with `pip install matplotlib==3.7.3`

@rythorpe @jasmainak this might have to do with #586 which really should just be a temporary fix and could be revisited

**Comment by jasmainak** [comment]
I noticed as well. We really shouldn't be pinning versions. Perhaps a good starting issue for the ccv folks

**Comment by jasmainak** [comment]
The same very likely! @gtdang jupyter widgets made an API breaking change with the 8.0 release. See here: https://ipywidgets.readthedocs.io/en/latest/user_migration_guides.html

We need to migrate our code to this version. It's a good opportunity to read the GUI code and understanding its structure.

**Comment by gtdang** [comment]
So I started poking into this issue as well as the pinning of the voila/ipywidgets issue. 

**Good news:** Using the latest versions of ipywidgets and voila I was able to get the widget up and running. 

**Bad news:** Default plots are not displaying at the end of simulation. 

**Consolation:** The plots generate when you manually create a figure, including the dipole plots!

**Environment:** 
Python 3.9.16
ipywidgets 8.1.1, ipympl 0.9.3, voila 0.5.5, matplotlib 3.8.2

There was no javascript error like in #585 #586 but rather an error in title assignment of the accordion widget due to the API breaking changes @jasmainak mentioned. This minor fix allows the widget to launch without error. 

Issue is that the plots don't display automatically after the simulation concludes. 
![Screenshot 2023-12-04 at 3 53 44 PM](https://github.com/jonescompneurolab/hnn-core/assets/53052793/6b613677-2605-4258-8a9e-40abfe9294d9)


However if you manually generate the visualizations the work. Even the problematic dipole plots. And this is using the latest version of matplotlib.

![Screenshot 2023-12-04 at 3 54 24 PM](https://github.com/jonescompneurolab/hnn-core/assets/53052793/9a7db7fb-8c27-40b7-98a1-f9b9c3ddea22)


Since the plots do show up with manual generation, the issue with the plots showing up after simulation is probably just some issue with a callback function at simulation conclusion. I'll try to figure that out tomorrow and get these changes into a PR.

**Comment by gtdang** [comment]
I was mistaken previously and was using Matplotlib v7.7.4 and so the dipole plots worked.  I started looking into the problem again and found the source of the issue to be the `prop_cycler` iterator being removed from `ax._get_lines` in Matplotlib 8.x  [mpl Issue 26831](https://github.com/matplotlib/matplotlib/issues/26831) We use this in the _viz_manager module in `_update_ax` function for the PSD and Dipole plots to cycle to the next line color. I'm assuming this important for when the axis is called on again to add another simulation. 

The issue is not something matplotlib is intending to fix so we'll have to look into a work-around.
