### ISSUE TITLE
BUG: Deleting drives in GUI after file upload prevents loading of the same file

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#698]
As title states, found by @gtdang

**Comment by gtdang** [comment]
ah. Seems like this bug just happened because of what we were doing with testing the FileUpload counter. I had commented out the resetting of the widget to show the counter incrementing to 1. We decided to continue to zero it instead. This actually resolves this. Good to know for if we ever want to restore the counter functionality, but I think this can be closed.
