### ISSUE TITLE
Add Virtual Environment Directories to `.gitignore`

### ISSUE THREAD

**Issue by samadpls** [jonescompneurolab/hnn-core#738]
I'd like to propose adding the following lines to `.gitignore` file to prevent virtual environment directories from being tracked by Git:

```
# Virtual environments
env/
venv/
ENV/
```
## Explanation:
- Virtual environments are project-specific and contain dependencies that shouldn't be committed to the main repository.

# Benefits: 
- New contributors to this repo, **like myself**, won't have to worry about accidentally committing virtual environment directories, leading to a smoother onboarding experience.

**Comment by jasmainak** [comment]
@samadpls please feel free to make a pull request !

**Comment by rythorpe** [comment]
I'm not opposed to this; however, I do feel like the underlying issue here is very user-specific. Personally, I wouldn't keep a virtual environment directory for a project within the source code of the project itself. There are a myriad of tools that developers and/or advanced users might opt to include within the source code of a project, but it is up to them to do so sparingly and to handle [local gitignore rules](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) on their personal machines.

**Comment by gtdang** [comment]
I agree with @rythorpe. Seems to be user specific. I do keep my virtual environments within project directories but I don't follow the venv naming convention because I have different environment builds to test out different python or dependency versions.  Perhaps linking to how to update your `.git/info/exclude` would be a good addition to the contributors guide?

**Comment by jasmainak** [comment]
`.gitignore` tends to include a broad set of files ... I checked a few repos : [mne](https://github.com/mne-tools/mne-python/blob/main/.gitignore) and [cookiecutter project](https://github.com/cookiecutter/cookiecutter/blob/main/.gitignore) for e.g., and they have a long .gitignore

I'm not against adding guidelines for better use of `git` but it adds an extra set up step for new contributors ...

**Comment by gtdang** [comment]
Yeah I suppose it's minor overhead and with very little risk, and is convenient for those who do use venv. Is there a recommended environment manager for this project?

**Comment by rythorpe** [comment]
That's fair @jasmainak and @gtdang. Let's move forward with with addressing this as @samadpls suggested.

Re: recommended environment manager, I think most of us use conda environments, but IDK if it truly matters.
