### ISSUE TITLE
GUI: Incomplete Plot types after loading data

### ISSUE THREAD

**Issue by kmilo9999** [jonescompneurolab/hnn-core#832]
Third Bug reported by Dylan

After loading data, the plot types dropdown in the figures control tab doesnt contain all the set of possible plot types.

current dipole
layer2 dipole
layer5 dipole
PSD
spectrogram

Missing:
'spikes', 'input histogram', 'network'

**Comment by kmilo9999** [comment]
@ntolley @gtdang 

This problem comes from PR #616 [this ](https://github.com/jonescompneurolab/hnn-core/pull/616/commits/8b9af574ae8c54ce6fac4c303944a88dfe212b9b) commit.

```
     sim_name_default = simulation_names[-1]

    if data['simulations'][sim_name_default]['net'] is None:
        valid_plot_types = [
            pt for pt in _plot_types if pt not in _ext_data_disabled_plot_types
        ]
    else:
        valid_plot_types = _plot_types
```

The plot types dropdown list values depend on the type of the last simulation in the  `data['simulations']` dictionary.
This code is executed after running a simulation, loading data or pressing the 'Make figure' button.

**Comment by ntolley** [comment]
Trying to think of what a clean solution is here, The only plots that make sense to overlay are 
- current dipole
- layer2 dipole
- layer5 dipole
- PSD

The spectrogram should be excluded since it used `imshow` and can't simultaneously show two sets of data

I think the correct behavior would be to have `valid_plot_types` depend on the currently selected `Data to compare`, so perhaps a callback that updates the `plot types` whenever you selected a different `Data to compare`

What do you think?

**Comment by gtdang** [comment]
I think we should remove this logic. It's making an assumption of what a user's next action will definitely be adding observed data to a plot. That's not always the case.

**Comment by gtdang** [comment]
We discussed this more at today's dev-sync. 

* The limiting of the plot types logic is in place for when selecting simulation vs loaded data to plot. We do want the limiting of plot types for loaded data. 
* The problem is that when creating a new figure. It decides to set defaults based on the last item stored in the `data` object, which stores both simulation and loaded data. If the data is loaded last, all new figure panes will start with plot types for loaded data. 

The solution is to initialize new figure panes with the last simulation and not loaded data.
